syntax = "proto3";
package filepriv;

message ServidorCandidato {
  int32 id = 1;
  string host = 2;
  int32 porta = 3;
  int32 arquivos_armazenados = 4;
}

message MetadadosUpload {
  int32 usuario_id = 1;
  string nome_arquivo = 2;
  string tipo_arquivo = 3;
  repeated ServidorCandidato servidores_disponiveis = 4;
}

message ArquivoChunkUpload {
  oneof conteudo {
    MetadadosUpload metadados = 1;
    bytes pedaco = 2;
  }
}

message RespostaUpload {
  bool sucesso = 1;
  string mensagem_erro = 2;
  string chave_referencia = 3;
  int32 servidor_id = 4;
  int32 tamanho = 5;
  string hash = 6;
}

service ProcessadorArquivo {
  rpc EnviarArquivo(stream ArquivoChunkUpload) returns (RespostaUpload);
}