services:
  postgres:
    image: postgres:16.2
    container_name: filepriv_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filepriv_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filepriv_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rust-grpc:
    build:
      context: .
      dockerfile: ./src/rust/Dockerfile
    container_name: filepriv_rust_grpc
    restart: always
    ports:
      - "50051:50051"
    volumes:
      - ./chaves_ssh/id_rsa:/etc/filepriv/chaves_ssh/id_rsa:ro
    depends_on:
      postgres:
        condition: service_healthy

  node-api:
    build:
      context: .                
      dockerfile: ./src/node/Dockerfile 
    container_name: filepriv_node_api
    restart: always
    ports:
      - "443:443"
    environment:
      RUST_GRPC_ADDR: rust-grpc:50051
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rust-grpc:
        condition: service_started
    command: sh -c "npx prisma db push && node src/app.js"

volumes:
  pgdata: